### PR TITLE
#334 revive datapusher using datawagovau/datapusher fork

### LINKED ISSUE #334: Vanilla datacats environment fails to start with AttributeError
Ok, here's a tricky one. My system should be up to date with:
* apt-get upgraded Ubuntu 14.04 VM
* fresh datacats master install (1.1.0)
* fresh docker install (updated) via `wget -qO- https://get.docker.com/ | sh`
* fresh datacats images via `datacats pull -a`

I've got a handful of existing datacats environments running on that VM which all work fine and can be stopped/restarted. However, creating a new datacats environment, or running `datacats install` inside an existing one will result in a crashing ckan instance.

Live example: 
`datacats create --ckan latest --site-url http://minesweeper.alpha.data.wa.gov.au minesweeper PORT`
creates http://minesweeper.alpha.data.wa.gov.au/ which initially works fine, but as soon as I login (using the admin account created during `datacats create`), it crashes with error trace:

```
Debug at: http://minesweeper.alpha.data.wa.gov.au/_debug/view/1443596557
2015-09-30 07:04:27,533 INFO  [ckan.lib.base]  /images/icons/ckan.ico render time 0.004 seconds
Traceback (most recent call last):
  ...
File "/project/ckan/ckan/model/activity.py", line 298, in dashboard_activity_list
    q = _dashboard_activity_query(user_id, limit + offset)
  File "/project/ckan/ckan/model/activity.py", line 283, in _dashboard_activity_query
    q1 = _user_activity_query(user_id, limit)
  File "/project/ckan/ckan/model/activity.py", line 126, in _user_activity_query
    return _activities_union_all(q1, q2)
  File "/project/ckan/ckan/model/activity.py", line 96, in _activities_union_all
    return model.Session.query(model.Activity).select_entity_from(
AttributeError: 'Query' object has no attribute 'select_entity_from'
```
Hitting /user/logout restores a working CKAN again.

This happens with both `--ckan latest` and `--ckan 2.4`.

If I run `datacats install` in an existing (previously working) environment, datapusher will install https://github.com/okfn/ckan-service-provider/archive/stable.zip which in turn pulls in SQLAlchemy==0.7.8 which in turn collides with latest (vanilla) ckanext-spatial's philosophy on GeoAlchemy2. Strangely, the relevant test in ckanext-spatial which tests for GeoAlchemy versions has been around since well before I ran my last (working) ckan installs.

Where could I have gone wrong? To my knowledge, my datacats installation, docker images, docker installation, and the datacats environment "minesweeper" are vanilla and up to date. 
Any pointers welcome!

update: 
```
(ckan)ubuntu@ip-172-31-22-195:/var/projects/ckan/boom$ datacats shell
Error response from daemon: Cannot start container 5d212a950796f3394e943c6935ec4d5c26097aee1d05298fc51fd26a0c8b270d: Cannot link to a non running container: /datacats_datapusher_boom_primary AS /gloomy_poincare/datapusher
```

`docker ps` confirms that datapusher only runs for the (working) site. So why is datapusher not running on my end? Shouldn't a `datacats reload` also restart the datapusher container?

### PR DESCRIPTION
**Pull request by florianm**
which uses datawagovau/ckanserviceprovider, which in turn does not hard-code SQLAlchemy and requests versions any more.

## Try
```
git clone https://github.com/datawagovau/datacats.git
datacats$ python setup.py install
datacats$ datacats pull -a
datacats/docker$ docker build -t datacats/ckan ckan/
```
## Pros
* uses datawagovau forks for datapusher and ckanserviceprovider
* datapusher works again (probably) or at least starts

## Cons
http://boom.alpha.data.wa.gov.au/ still blows up after login with AttributeError: 'Query' object has no attribute 'select_entity_from' where `/project/ckan/ckan/model/activity.py`L96 tries to get SQLAlchemy to `_union_all` activities for the user dashboard.

## Why
Trying to help @JackMc  @deniszgonjanin to fix #334

### CODE REVIEW

**Comment by florianm** [comment]
Confirming @deniszgonjanin a site using my customised "ckan latest" image _without_ datapusher still works, e.g. http://waitwaitboom.alpha.data.wa.gov.au/ created with 
```
datacats create --ckan latest --no-datapusher --site-url http://waitwaitboom.alpha.data.wa.gov.au waitwaitboom 5010
```
As expected, circle ci blows up with the datapusher container failing for ckan 2.3 which I haven't modified.

**Comment by wardi** [comment]
I made the select_entity_from change for sqlalchemy 0.9, is this related? https://github.com/ckan/ckan/commit/a4de57e5

**Comment by florianm** [comment]
it's the line that ultimately fails on my end. Do I understand you
correctly that this is a change in ckan, which is now part of the "latest"
datacats image, and that it will work with sqlalchemy > 0.9?

related question - if I want to install a ckan extension into a datacats
environment without calling datacats install, do I need to do so from the
datacats shell?

**Comment by wardi** [comment]
Yes, you can use "datacats shell" then "setup.py develop" to install extensions without using "datacats install"

Yes, this change is in the latest ckan versions. If you want to use an older sqlalchemy you'll have to reverse that change, but otherwise as best I can tell it works the same

**Comment by wardi** [comment]
Is this fixed by #342 ?

**Comment by florianm** [comment]
@wardi my end looks good with datacats@master, freshly pulled datacats images, ckan@latest. Even the wrong SQLAlchemy version (0.7.8, god knows where that came from) is gone. Closing this issue, thanks for the fix!
