### ISSUE TITLE
Error on create with 2.3 image

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#341]
Testing a fix for #334 
`datacats create --ckan=2.3 test334`
```
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Users/dz/source/datacats/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/Users/dz/source/datacats/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/Users/dz/source/datacats/datacats/cli/create.py", line 97, in <lambda>
    lambda: environment.update_ckan_ini(skin=create_skin),
  File "/Users/dz/source/datacats/datacats/environment.py", line 330, in update_ckan_ini
    self.run_command(command=command, rw_project=True)
  File "/Users/dz/source/datacats/datacats/environment.py", line 852, in run_command
    commit=True, stream_output=stream_output)
  File "/Users/dz/source/datacats/datacats/docker.py", line 212, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /usr/lib/ckan/bin/paster --plugin=ckan config-tool /project/development.ini -e sqlalchemy.url = postgresql://<hidden> ckan.datastore.read_url = postgresql://<hidden> ckan.datastore.write_url = postgresql://<hidden> ckan.datapusher.url = http://datapusher:8800 solr_url = http://solr:8080/solr ckan.storage_path = /var/www/storage ckan.plugins = datastore resource_proxy text_view datapusher recline_grid_view recline_graph_view test334_theme ckan.site_title = test334 ckan.site_logo = ckan.auth.create_user_via_web = false
    Docker Error Log:
    Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 103, in run
    command = commands[command_name].load()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/project/ckan/ckan/lib/cli.py", line 12, in <module>
    import ckan.logic as logic
  File "/project/ckan/ckan/logic/__init__.py", line 8, in <module>
    import ckan.model as model
  File "/project/ckan/ckan/model/__init__.py", line 7, in <module>
    import vdm.sqlalchemy
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/vdm/sqlalchemy/__init__.py", line 31, in <module>
    from base import *
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/vdm/sqlalchemy/base.py", line 7, in <module>
    from sqlalchemy import *
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/__init__.py", line 52, in <module>
    from sqlalchemy.types import (
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/types.py", line 27, in <module>
    from sqlalchemy import exc, schema
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/schema.py", line 33, in <module>
    from sqlalchemy import event, events
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/__init__.py", line 7, in <module>
    from .api import CANCEL, NO_RETVAL, listen, listens_for, remove, contains
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/api.py", line 13, in <module>
    from .base import _registrars
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/base.py", line 42, in <module>
    class _Dispatch(object):
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/base.py", line 104, in _Dispatch
    @util.hybridmethod
AttributeError: 'module' object has no attribute 'hybridmethod'
```

**Comment by JackMc** [comment]
This may be a symptom of the whole different versions of SQLAlchemy in service provider and CKAN

**Comment by deniszgonjanin** [comment]
Right, everything works fine with non-2.3 images

**Comment by JackMc** [comment]
So we need to pin the version on SQLAlchemy I guess... Or even worse hack one of CKAN or service provider to play nice with newer SQLAlchemy

**Comment by deniszgonjanin** [comment]
ckan-service-provider doesn't actually need the specific SQLAlchemy version it says it does. My fork of it lets the SQLAlchemy version float, which should play nice with anything else

**Comment by JackMc** [comment]
We are using your fork for the version that's on docker hub

**Comment by JackMc** [comment]
(Except for 2.3). Should I stick it in the 2.3 image?

**Comment by deniszgonjanin** [comment]
Yea, go for it. It should almost certainly be fine :grin:

**Comment by wardi** [comment]
this is working on circleci, what are we missing in our tests to see the failure?

**Comment by JackMc** [comment]
Does this work now for you @deniszgonjanin?

**Comment by deniszgonjanin** [comment]
Indeed it does
