### ISSUE TITLE
Issue with detacats deploy command

### ISSUE THREAD

**Issue by byndcivilization** [datacats/datacats#218]
I'm having trouble deploying. Command completes the 'sending incremental file list' portion but errors with the following message.

sent 880,854 bytes  received 335,307 bytes  83,873.17 bytes/sec
total size is 34,283,184  speedup is 28.19
Traceback (most recent call last):
  File "/Users/cperry/anaconda/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.11.1', 'console_scripts', 'datacats')()
  File "/Users/cperry/anaconda/lib/python2.7/site-packages/datacats/cli/main.py", line 94, in main
    return command_fn(environment, opts, user_profile)
  File "/Users/cperry/anaconda/lib/python2.7/site-packages/datacats/cli/deploy.py", line 45, in deploy
    profile.deploy(environment, target_name, stdout)
  File "/Users/cperry/anaconda/lib/python2.7/site-packages/datacats/userprofile.py", line 184, in deploy
    ro=environment.remote_command_binds(self),
AttributeError: 'Environment' object has no attribute 'remote_command_binds'

**Comment by wardi** [comment]
We're on it. I think this was a bad merge.

**Comment by JackMc** [comment]
Hi @byndcivilization thanks for the report!

We have backported a fix of this issue to the 0.11 release. Can you try this command to install the new version and report back that it works or doesn't for you:
```
pip install -e git+http://github.com/datacats/datacats.git@100f245a5#egg=datacats
```

**Comment by JackMc** [comment]
If it does work we'll do a release of 0.11.2 or the like :smile:

**Comment by wardi** [comment]
I'm sure this is what you ran into. I've released 0.11.2, please reinstall and try again

**Comment by byndcivilization** [comment]
Perfect thanks!
